import { PricingPlan, PlanFeature } from "@/types/pricing/pricing.type";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "essential",
    name: "Essential",
    priceMonthly: "Free",
    priceYearly: "Free",
    currency: "",
    descriptionPrefix: "Start with:",
    features: [
      "Universal Profile",
      "Manual Linking",
      "Social Search",
      "Activity Feed",
      "Basic Filters",
      "Content Preview",
    ],
    buttonText: "Get started",
    buttonVariant: "outline",
  },
  {
    id: "creator",
    name: "Creator",
    badge: "Best choice",
    priceMonthly: 190,
    priceYearly: 152, // 20% discount (190 * 0.8)
    currency: "SEK",
    descriptionPrefix: "Everything in Essential, plus:",
    features: [
      "Verified Identity",
      "AI Captions",
      "Smart Hashtags",
      "Post Scheduling",
      "Smart Suggestions",
      "Data export (CSV/PDF)",
      "Admin controls",
      "Media Filters",
    ],
    buttonText: "Try for free",
    buttonVariant: "solid",
  },
  {
    id: "visionary",
    name: "Visionary",
    priceMonthly: 490,
    priceYearly: 392, // 20% discount (490 * 0.8)
    currency: "SEK",
    descriptionPrefix: "Everything in Creator, plus:",
    features: [
      "Deep Web Search",
      "Advanced Filters",
      "Saved Collections",
      "AI Time Suggestions",
      "Advanced Analytics",
      "Automation Tools",
      "Priority Search",
      "Early AI Features",
    ],
    buttonText: "Try for free",
    buttonVariant: "solid",
  },
];

export const COMPARISON_FEATURES: { name: string; essential: boolean; creator: boolean; visionary: boolean }[] = [
  { name: "Universal Profile", essential: true, creator: true, visionary: true },
  { name: "Manual Profile Linking", essential: true, creator: true, visionary: true },
  { name: "Cross-Platform Search", essential: true, creator: true, visionary: true },
  { name: "Activity Feed", essential: true, creator: true, visionary: true },
  { name: "Basic Filters", essential: false, creator: true, visionary: true },
  { name: "Verified Identity", essential: false, creator: true, visionary: true },
  { name: "AI Captions", essential: false, creator: true, visionary: true },
  { name: "Smart Hashtags", essential: false, creator: true, visionary: true },
  { name: "Content Scheduling", essential: false, creator: true, visionary: true },
  { name: "Advanced Analytics", essential: false, creator: false, visionary: true },
  { name: "AI Time Suggestions", essential: false, creator: false, visionary: true },
  { name: "Saved Collections", essential: false, creator: false, visionary: true },
  { name: "Deep Web Search", essential: false, creator: false, visionary: true },
  { name: "Automation Tools", essential: false, creator: false, visionary: true },
  { name: "Early AI Features", essential: false, creator: false, visionary: true },
];